set_cover_position:
  target:
    entity:
      domain: cover
  fields:
    position:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

open_cover:
  target:
    entity:
      domain: cover

close_cover:
  target:
    entity:
      domain: cover

apply_memory:
  target:
    entity:
      domain: cover

apply_mode:
  target:
    entity:
      domain: cover
  fields:
    mode:
      required: true
      example: "Nuit"
      selector:
        text:

compute_shade_position:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: cover

get_mode_position:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: cover
    mode:
      required: true
      example: "Nuit"
      selector:
        text:

reload:
